apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - postgres.yaml
  - configmap.yaml
  - pgadmin-deployment.yaml
  - ingress.yaml

commonLabels:
  app: eco-go

namePrefix: eco-go-
