apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZWNvZ28uY29t    
  PGADMIN_DEFAULT_PASSWORD: ZWNvZ28xMjM=  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eco-go
      component: pgadmin
  template:
    metadata:
      labels:
        app: eco-go
        component: pgadmin
    spec:
      containers:
      - name: pgadmin-container
        image: dpage/pgadmin4:7
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: eco-go
    component: pgadmin
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP