name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'       
        extensions: mbstring, json, pdo, mysqli

    # Step 3: Install dependencies 
    - name: Install dependencies
      run: composer install
      continue-on-error: true    

    # Step 4: Run a basic PHP linter
    - name: PHP Syntax Check
      run: php -l index.php

    # Step 5: Run tests 
    - name: Run PHPUnit Tests
      run: |
        if [ -f composer.json ]; then
          vendor/bin/phpunit
        else
          echo "No tests to run."
        fi
