name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Adjust based on your PHP version
        extensions: mbstring, json, pdo, mysqli

    # Install dependencies
    - name: Install dependencies
      run: composer install

    # Run PHP Linter
    - name: Run PHP Linter
      run: php -l public/index.php

    # Run JavaScript Tests
    - name: Run JS Tests
      run: |
        npm install
        npm test
